# -------------------------------------------------------------------------
#  Copyright 2026 Ratha SIV. All rights reserved.
#  Apache-2.0 license
# -------------------------------------------------------------------------

name: build-template-cpu-pure-python

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: project
      PACKAGE_GIT_URL: "https://github.com/user/project.git"
      PACKAGE_GIT_TAG: ""
    steps:
    - name: Set up Python 3.14
      uses: actions/setup-python@v6
      with:
        python-version: '3.14'
    - name: Clone ${{ env.PACKAGE_NAME }}
      run: |
        if [ -n "${PACKAGE_GIT_TAG}" ]; then
          git clone -b "${PACKAGE_GIT_TAG}" "${PACKAGE_GIT_URL}" "${PACKAGE_NAME}"
        else
          git clone "${PACKAGE_GIT_URL}" "${PACKAGE_NAME}"
        fi
    - name: Install build tools
      run: |
        python -m pip install -U pip
        python -m pip install -U build wheel setuptools
    - name: Build wheel (CPU only, pure Python)
      run: |
        mkdir -p dist
        python -m build --no-isolation --skip-dependency-check $PACKAGE_NAME --outdir dist
    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: dist-${{ env.PACKAGE_NAME }}
        path: dist/*
