# -------------------------------------------------------------------------
#  Copyright 2026 Ratha SIV. All rights reserved.
#  Apache-2.0 license
# -------------------------------------------------------------------------

# There are 7 main roots for compute platform, which are defined as follows:
# 1. 'any' for both cpu and gpu
# 2. 'cu113' for consumer & workstation gpu with cuda 11.3
# 3. 'cu121' for consumer & workstation gpu with cuda 12.1
# 4. 'cu126' for consumer & workstation gpu with cuda 12.6
# 5. 'cu128' for consumer & workstation gpu with cuda 12.8
# 6. 'cu130' for consumer & workstation gpu with cuda 13.0
# 7. 'cu130d' for data center gpu with cuda 13.0

# The index directary structure is defined as:
# {compute_platform}/{package_name}/index.html

# Each index.html looks like contains a list of href link to the wheel files, which are defined as:
# <a href="{base_url}/{release_tag}/{dist}">{dist}</a><br>

# Example of a full url for a wheel file:
# https://github.com/rathaumons/bevfusionx-index/releases/download/v0.3.2-torchpack-any/torchpack-0.3.2+bevfusionx-py3-none-any.whl

# Base url for wheel are stored in:
base_url: https://github.com/rathaumons/bevfusionx-index/releases/download

# indexations
indexes:
  - compute_platform: any
    packages:
      - project_name: torchpack
        package_name: torchpack
        version: v0.3.2
        release_tag: v0.3.2-torchpack-any
        dist:
          - torchpack-0.3.2+bevfusionx-py3-none-any.whl
          - torchpack-0.3.2+bevfusionx.tar.gz
  - compute_platform: cu113
    packages:
      - project_name: flash-attention
        package_name: flash-attn
        version: v1.2.1
        release_tag: v1.2.1-flash-attention-cu113
        dist:
          - flash_attn-1.2.1+bevfusionx-cp39-cp39-linux_x86_64.whl
          - flash_attn-1.2.1+bevfusionx.tar.gz
      - project_name: mmcv
        package_name: mmcv-full
        version: v1.7.3
        release_tag: v1.7.3-mmcv-cu113
        dist:
          - mmcv_full-1.7.3+bevfusionx-cp39-cp39-linux_x86_64.whl
          - mmcv_full-1.7.3+bevfusionx.tar.gz
  - compute_platform: cu121
    packages:
      - project_name: flash-attention
        package_name: flash-attn
        version: v1.2.1
        release_tag: v1.2.1-flash-attention-cu121
        dist:
          - flash_attn-1.2.1+bevfusionx-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl
          - flash_attn-1.2.1+bevfusionx.tar.gz
      - project_name: mmcv
        package_name: mmcv-full
        version: v1.7.3
        release_tag: v1.7.3-mmcv-cu121
        dist:
          - mmcv_full-1.7.3+bevfusionx-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl
          - mmcv_full-1.7.3+bevfusionx.tar.gz
  - compute_platform: cu126
    packages:
      - project_name: flash-attention
        package_name: flash-attn
        version: v1.2.1
        release_tag: v1.2.1-flash-attention-cu126
        dist:
          - flash_attn-1.2.1+bevfusionx-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl
          - flash_attn-1.2.1+bevfusionx.tar.gz
      - project_name: mmcv
        package_name: mmcv-full
        version: v1.7.3
        release_tag: v1.7.3-mmcv-cu126
        dist:
          - mmcv_full-1.7.3+bevfusionx-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl
          - mmcv_full-1.7.3+bevfusionx.tar.gz
  - compute_platform: cu128
    packages:
      - project_name: flash-attention
        package_name: flash-attn
        version: v1.2.1
        release_tag: v1.2.1-flash-attention-cu128
        dist:
          - flash_attn-1.2.1+bevfusionx-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl
          - flash_attn-1.2.1+bevfusionx.tar.gz
      - project_name: mmcv
        package_name: mmcv-full
        version: v1.7.3
        release_tag: v1.7.3-mmcv-cu128
        dist:
          - mmcv_full-1.7.3+bevfusionx-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl
          - mmcv_full-1.7.3+bevfusionx.tar.gz
  - compute_platform: cu130d
    packages:
      - project_name: flash-attention
        package_name: flash-attn
        version: v1.2.1
        release_tag: v1.2.1-flash-attention-cu130d
        dist:
          - flash_attn-1.2.1+bevfusionx-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl
          - flash_attn-1.2.1+bevfusionx.tar.gz
      - project_name: mmcv
        package_name: mmcv-full
        version: v1.7.3
        release_tag: v1.7.3-mmcv-cu130d
        dist:
          - mmcv_full-1.7.3+bevfusionx-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl
          - mmcv_full-1.7.3+bevfusionx.tar.gz
  - compute_platform: cu130
    packages:
      - project_name: flash-attention
        package_name: flash-attn
        version: v1.2.1
        release_tag: v1.2.1-flash-attention-cu130
        dist:
          - flash_attn-1.2.1+bevfusionx-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl
          - flash_attn-1.2.1+bevfusionx.tar.gz
      - project_name: mmcv
        package_name: mmcv-full
        version: v1.7.3
        release_tag: v1.7.3-mmcv-cu130
        dist:
          - mmcv_full-1.7.3+bevfusionx-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl
          - mmcv_full-1.7.3+bevfusionx.tar.gz
