# -------------------------------------------------------------------------
#  Copyright 2026 Ratha SIV. All rights reserved.
#  Apache-2.0 license
# -------------------------------------------------------------------------

# Prebuilt wheels of cumm-spconv for consumer, workstation, and jetson is 
# already available here: https://ratharog.github.io/cumm-spconv/

name: build cumm-spconv

on:
  workflow_dispatch:

jobs:

  build_cumm_cuda_13d:
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: "cumm-cu130"
      PACKAGE_GIT_URL: "https://github.com/rathaROG/cumm-gpu.git"
      PACKAGE_GIT_TAG: "v0.9.1"
      WHL_PYTHON_VERSIONS: "['3.11']"
      INSTALL_TORCH: 0
      INSTALL_EXTRA: ""
      INSTALL_TXT: ""
      PIP_EXTRA_INDEX_URL: ""
      CUDA_ARCH_LIST: ""
      NVIDIA_ARCH_TYPE: "dcen"
      NVIDIA_ARCH_MIN: 75
      AUDITWHEEL_EXCL_LIBS: "['']"
      BUILD_ISOLATION: 1
      BUILD_ADDITIONAL_VARS: "CUMM_DISABLE_JIT='1' CUMM_CUDA_VERSION='13.0' CUMM_CUDA_ARCH_LIST='7.5;8.0;8.6;8.9;9.0;10.0;10.3;12.0+PTX'"
    strategy:
      fail-fast: false
      matrix:
        cuda-version: ['130']
    steps:
      - name: Clean CI runner
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/local/share/chromium
          docker system prune -af
      - uses: actions/checkout@v6
      - name: Pull cu${{ matrix.cuda-version }} image from Docker Hub
        run: docker pull ratharog/manylinux_2_28_x86_64:cu${{ matrix.cuda-version }}
      - name: Build cu${{ matrix.cuda-version }} wheels
        run: |
          if [ -n "${PACKAGE_GIT_TAG}" ]; then
            git clone -b "${PACKAGE_GIT_TAG}" "${PACKAGE_GIT_URL}" "${PACKAGE_NAME}"
          else
            git clone "${PACKAGE_GIT_URL}" "${PACKAGE_NAME}"
          fi
          chmod +x tools/build-linux-wheels.sh
          docker run --rm \
            -e PACKAGE_NAME="${PACKAGE_NAME}" \
            -e PYTHON_VERSIONS="${WHL_PYTHON_VERSIONS}" \
            -e INSTALL_TORCH="${INSTALL_TORCH}" \
            -e INSTALL_EXTRA="${INSTALL_EXTRA}" \
            -e INSTALL_TXT="${INSTALL_TXT}" \
            -e PIP_EXTRA_INDEX_URL="${PIP_EXTRA_INDEX_URL}" \
            -e CUDA_ARCH_LIST="${CUDA_ARCH_LIST}" \
            -e NVIDIA_ARCH_TYPE="${NVIDIA_ARCH_TYPE}" \
            -e NVIDIA_ARCH_MIN="${NVIDIA_ARCH_MIN}" \
            -e AUDITWHEEL_EXCL_LIBS="${AUDITWHEEL_EXCL_LIBS}" \
            -e BUILD_ISOLATION="${BUILD_ISOLATION}" \
            -e BUILD_ADDITIONAL_VARS="${BUILD_ADDITIONAL_VARS}" \
            -e CUDA_VERSION="${{ matrix.cuda-version }}" \
            -v "$(pwd)":/io \
            ratharog/manylinux_2_28_x86_64:cu${{ matrix.cuda-version }} \
            bash -c "source /etc/bashrc && /io/tools/build-linux-wheels.sh"
      - name: Archive cu${{ matrix.cuda-version }} wheels
        uses: actions/upload-artifact@v7
        with:
          name: dist-${{ env.PACKAGE_NAME }}-cu${{ matrix.cuda-version }}d
          path: dist/*


  build_spconv_cuda_13d:
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: "spconv-cu130"
      PACKAGE_GIT_URL: "https://github.com/rathaROG/spconv-gpu.git"
      PACKAGE_GIT_TAG: "v2.4.1"
      WHL_PYTHON_VERSIONS: "['3.11']"
      INSTALL_TORCH: 0
      INSTALL_EXTRA: ""
      INSTALL_TXT: ""
      PIP_EXTRA_INDEX_URL: "https://ratharog.github.io/cumm-spconv/"
      CUDA_ARCH_LIST: ""
      NVIDIA_ARCH_TYPE: "dcen"
      NVIDIA_ARCH_MIN: 75
      AUDITWHEEL_EXCL_LIBS: "['']"
      BUILD_ISOLATION: 1
      BUILD_ADDITIONAL_VARS: "CUMM_DISABLE_JIT='1' SPCONV_DISABLE_JIT='1' CUMM_CUDA_VERSION='13.0' CUMM_CUDA_ARCH_LIST='7.5;8.0;8.6;8.9;9.0;10.0;10.3;12.0+PTX'"
    strategy:
      fail-fast: false
      matrix:
        cuda-version: ['130']
    steps:
      - name: Clean CI runner
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/local/share/chromium
          docker system prune -af
      - uses: actions/checkout@v6
      - name: Pull cu${{ matrix.cuda-version }} image from Docker Hub
        run: docker pull ratharog/manylinux_2_28_x86_64:cu${{ matrix.cuda-version }}
      - name: Build cu${{ matrix.cuda-version }} wheels
        run: |
          if [ -n "${PACKAGE_GIT_TAG}" ]; then
            git clone -b "${PACKAGE_GIT_TAG}" "${PACKAGE_GIT_URL}" "${PACKAGE_NAME}"
          else
            git clone "${PACKAGE_GIT_URL}" "${PACKAGE_NAME}"
          fi
          chmod +x tools/build-linux-wheels.sh
          docker run --rm \
            -e PACKAGE_NAME="${PACKAGE_NAME}" \
            -e PYTHON_VERSIONS="${WHL_PYTHON_VERSIONS}" \
            -e INSTALL_TORCH="${INSTALL_TORCH}" \
            -e INSTALL_EXTRA="${INSTALL_EXTRA}" \
            -e INSTALL_TXT="${INSTALL_TXT}" \
            -e PIP_EXTRA_INDEX_URL="${PIP_EXTRA_INDEX_URL}" \
            -e CUDA_ARCH_LIST="${CUDA_ARCH_LIST}" \
            -e NVIDIA_ARCH_TYPE="${NVIDIA_ARCH_TYPE}" \
            -e NVIDIA_ARCH_MIN="${NVIDIA_ARCH_MIN}" \
            -e AUDITWHEEL_EXCL_LIBS="${AUDITWHEEL_EXCL_LIBS}" \
            -e BUILD_ISOLATION="${BUILD_ISOLATION}" \
            -e BUILD_ADDITIONAL_VARS="${BUILD_ADDITIONAL_VARS}" \
            -e CUDA_VERSION="${{ matrix.cuda-version }}" \
            -v "$(pwd)":/io \
            ratharog/manylinux_2_28_x86_64:cu${{ matrix.cuda-version }} \
            bash -c "source /etc/bashrc && /io/tools/build-linux-wheels.sh"
      - name: Archive cu${{ matrix.cuda-version }} wheels
        uses: actions/upload-artifact@v7
        with:
          name: dist-${{ env.PACKAGE_NAME }}-cu${{ matrix.cuda-version }}d
          path: dist/*
